import {
  Box,
  Card,
  CardBody,
  Center,
  Heading,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import ClientReview from "../components/pages/LandingPage/ClientReview/ClientReview";
import Header from "../components/pages/LandingPage/Header/Header";
import OurServices from "../components/pages/LandingPage/OurServices/OurServices";
import ProductIntro from "../components/pages/LandingPage/ProductIntro/ProductIntro";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box maxW={"container.xl"} mx={"auto"}>
        <Header />
        <ProductIntro />
        <OurServices />
        <ClientReview />
      </Box>
    </Box>
  );
}
